### ISSUE TITLE
USER STORY: As a user I want to have my own account so that I can write my own articles as well as like and comment on other people's articles

### ISSUE THREAD

**Issue by dev-timm** [dev-timm/DietaryYou#1]
EPIC: Account Registration 

As a user I want to have my own account so that I can write my own articles as well as like and comment on other people's articles

**Acceptance Criteria**

- [ ] user has to give the email address
- [ ] user has to set a password 
- [ ] user needs to confirm password
- [ ] all input fields are required
- [ ] after successful registration user gets redirected to the overview page

**Tasks**

- [ ] Task 1: Implement registration form
- [ ] Task 2: Add registration validation and error handling
- [ ] Task 3: Test functionality
