### ISSUE TITLE
USER STORY: As a user I want to edit my article so that I can update it at any time

### ISSUE THREAD

**Issue by dev-timm** [dev-timm/DietaryYou#10]
EPIC: Write Article

As a **user** I want to **edit my article** so that **I can update it at any time**

**Acceptance Criteria**

- [ ] User lands on edit page after clicking edit icon
- [ ] User sees confirmation/error alert after saving the updates

**Tasks**

- [ ] Task 1: Create edit form page of an existing article
- [ ] Task 2: Add edit icon next to the articles' headlines and link it to the edit form
- [ ] Task 3: Add error handling
- [ ] Task 4: Test functionality
