### ISSUE TITLE
USER STORY: As a user I want to view different articles so that I can inform myself about dietairy topics

### ISSUE THREAD

**Issue by dev-timm** [dev-timm/DietaryYou#12]
EPIC: View Article

As a **user** I want to **view different articles** so that **I can inform myself about dietairy topics**

**Acceptance Criteria**

- [ ] Clicking on an article on the homepage will open the article
- [ ] Article contains a headline, author, date and content

**Tasks**

- [ ] Task 1: Link thumbnail on homepage to article page
- [ ] Task 2: Style article page including author and date of release
- [ ] Task 3: Test functionality
