### ISSUE TITLE
USER STORY: As a user I want to like articles so that I can show my appreciation to other users

### ISSUE THREAD

**Issue by dev-timm** [dev-timm/DietaryYou#13]
EPIC: View Article

As a **user** I want to **like articles** so that **I can show my appreciation to other users**

**Acceptance Criteria**

- [ ] On top of each article is a heart icon with the total number of likes
- [ ] Clicking on heart icon will turn it red and increase the amount of likes by one
- [ ] Clicking again will remove the like and turn it back to grey

**Tasks**

- [ ] Task 1: Add like icon and total amount of likes
- [ ] Task 2: Change icon color when clicked
- [ ] Task 3: Increase/decrease counter by 1 when clicked
- [ ] Task 4: Test functionality
