### ISSUE TITLE
USER STORY: As a user I want to have quick access to the social media acounts so that I can follow them and get more updates 

### ISSUE THREAD

**Issue by dev-timm** [dev-timm/DietaryYou#15]
EPIC: Footer

As a **user** I want to **have quick access to the social media accounts** so that **I can follow them and get more updates** 

**Acceptance Criteria**

- [ ] Social media icons can be found in the footer
- [ ] Clicking on an icon will bring the user to the matching social media profile

**Tasks**

- [ ] Task 1: Add social media logos and link to corresponding pages
- [ ] Task 2: Test functionality
