### ISSUE TITLE
USER SORY: Admin Articles

### ISSUE THREAD

**Issue by dev-timm** [dev-timm/DietaryYou#16]
EPIC: Admin

As a **admin** I want to **create, read, update and delete articles via an admin platform** so that **I can start creating blog content**

**Acceptance Criteria**

- [ ] admin platform where admins can create, read, update and delete articles
- [ ] a filter system on the admin platform that helps keep the overviiew

**Tasks**

- [ ] Task 1: Create admin platform
- [ ] Task 2: Add all input fields required for a new Article
- [ ] Task 3: Add filter
- [ ] Task 3: Test functionality
