### ISSUE TITLE
USER STORY: As a user I want to log in so that I can like, comment and write articles

### ISSUE THREAD

**Issue by dev-timm** [dev-timm/DietaryYou#2]
EPIC: Log In

As a **user** I want to **log in** so that **I can like, comment and write articles**

**Acceptance Criteria**

- [ ] user has to type correct email address or username
- [ ] user has to type correct password
- [ ] after user logs in, they are redirected to the overview page
- [ ] if email or password is wrong an error alert is displayed

**Tasks**

- [ ] Task 1: Implement login form
- [ ] Task 2: Add login validation and error handling
- [ ] Task 3: Test functionality
