### ISSUE TITLE
USER STORY: Show Header

### ISSUE THREAD

**Issue by dev-timm** [dev-timm/DietaryYou#22]
EPIC: Header

As a **user** I want **to see a header on top of the page** so that **I have a way to register, login and navigate through the website** 

**Acceptance Criteria**

- [x] Contains logo that will lead to homepage
- [x] Displays log in link and sign up button (functionality will be implemented in a later ticket)

**Tasks**

- [x] Task 1: Create base.html page
- [x] Task 2: Add header with logo, log in link and sign up button
