### ISSUE TITLE
USER STORY: Homepage Hero

### ISSUE THREAD

**Issue by dev-timm** [dev-timm/DietaryYou#23]
EPIC: Introduction

As a **user** I want to **immediately get an understanding of the purpose of the app ** so that **I can decide if it contains the right value for me**

**Acceptance Criteria**

- [ ] A hero section is visible on top of the homepage 
- [ ] The hero section is only visible for users that are **not** logged in
- [ ] Her section contains a heading, sign up button and image 

**Tasks**

- [ ] Implement hero section on top of the homepage
- [ ] make sure hero section is only visible for visitors that are **not** logged in
