### ISSUE TITLE
USER STORY: Add Profile Page

### ISSUE THREAD

**Issue by dev-timm** [dev-timm/DietaryYou#25]
EPIC: Profile

As a **user** I want to **have the option to customise my user profile page** so that **I can share more about myself with other users**

**Acceptance Criteria**
- [ ] User can edit their profile page
- [ ] profile page consists of profile image, bio, hobbies and location
- [ ] Other users can see a profile page by clicking on the username

**Tasks**
- [ ] Add profile page
- [ ] Access page by clicking on account -> profile or on username
- [ ] Edit and display profile picture, bio, hobbies and location
