### ISSUE TITLE
USER STORY: As a user I want to have an option to reset the password so that I can access my account again if I forget my password

### ISSUE THREAD

**Issue by dev-timm** [dev-timm/DietaryYou#3]
EPIC: Log In

As a **user** I want to **have an option to reset the password** so that **I can access my account again if I forget my password**

**Acceptance Criteria**

- [ ] a link to reset the password can be found on the log in form
- [ ] user is asked to enter email address
- [ ] an email with a link is sent to the user to reset the password
- [ ] user can enter a new password

**Tasks**

- [ ] Task 1: Add link "Forgot Password" to log in form
- [ ] Task 2: Add new page with an email input field and submit button
- [ ] Task 3: Set up password reset functionality
- [ ] Task 4: Add error handling
- [ ] Task 5: Test functionality
