### ISSUE TITLE
As a user I want to log out of the account so that my account is more secure

### ISSUE THREAD

**Issue by dev-timm** [dev-timm/DietaryYou#5]
EPIC: Settings

As a **user** I want to **log out of the account** so that **my account is more secure**

**Acceptance Criteria**

- [ ] By clicking the "Log Out" button, user is logged out and a success alert is shown

**Tasks**

- [ ] Task 1: Set up logout functionality
- [ ] Task 2: Test functionality
