### ISSUE TITLE
USER STORY: Change settings

### ISSUE THREAD

**Issue by dev-timm** [dev-timm/DietaryYou#6]
EPIC: Settings

As a **user** I want to **change my email address, username and/or password** so that **I can increase the security of my account**

**Acceptance Criteria**

- [x] User can change email address by clicking on edit icon
- [x] User can change password by typing the current and new password
- [x] Changes re saved by clicking on "Update Settings" button

**Tasks**

- [x] Task 1: Add edit icon to email address
- [x] Task 2: Clicking on edit icon shows input fields
- [x] Task 3: Clicking "Update Settings" button saves the changes
- [x] Task 5: Test functionality
