### ISSUE TITLE
As a user I want to have the option to delete my account so that I don't have to bother if I'm not intersted in the service anymore

### ISSUE THREAD

**Issue by dev-timm** [dev-timm/DietaryYou#7]
EPIC: Settings

As a **user** I want to **have the option to delete my account** so that **I don't have to bother if I'm not interested in the service anymore**

**Acceptance Criteria**

- [ ] Delete account option displayed in the settings
- [ ] Clicking on "delete account" will display a warning window
- [ ] If the user clicks on the delete button, the account will be deleted

**Tasks**

- [ ] Task 1: Implement warning modal after user clicks on delete account link
- [ ] Task 2: Implement delete account functionality and remove account from the database
- [ ] Task 3: Test functionality
