### ISSUE TITLE
USER STORY: View most recent and popular articles

### ISSUE THREAD

**Issue by dev-timm** [dev-timm/DietaryYou#8]
EPIC: Article Overview

As a **user** I want **to see the most popular and recent articles** so that **I can easily find interesting topics to read**

**Acceptance Criteria**

- [x] User sees 3 of the most clicked and liked articles
- [x] User sees a list of the most recent articles

**Tasks**

- [x] Task 3: Add most popular articles section
- [x] Task 4: Add Recent Articles section
- [x] Task 6: Test functionality
