### ISSUE TITLE
USER STORY: Write Articles

### ISSUE THREAD

**Issue by dev-timm** [dev-timm/DietaryYou#9]
EPIC: Write Article

As a **user** I want to **write an article** so that **I can share my knowledge and tips about diets**

**Acceptance Criteria**

- [x] User clicks on the button "Create Article" in header which opens the editor
- [x] User can enter title and content of the article and then publish it by clicking "Post Article"

**Tasks**

- [ ] Task 1: Create new page for writing an article
- [ ] Task 2: Add button to header and link to new article page
- [ ] Task 3: Add markdown form that consists of a headline, content and a submit button
- [ ] Task 4: Publish article by clicking submit button
- [ ] Task 5: Add error handling
- [ ] Task 6: Test functionality
